name: TEST
permissions:
  contents: read
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-2022  ]
    runs-on: ${{ matrix.os }}
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Test Modeler
      run: |
        npm install puppeteer
        npm run test

    - name: Build distro (Linux)
      if: ${{ runner.OS == 'Linux' }}
      env:
        ELECTRON_GET_USE_PROXY: true
      run: npm run build -- --linux

    - name: Build distro (MacOS)
      if: ${{ runner.os == 'macOS' }}
      env:
        ELECTRON_GET_USE_PROXY: true
      run: npm run build -- --mac
      
    - name: Build distro (Windows)
      if: ${{ runner.os == 'Windows' }}
      env:
        ELECTRON_GET_USE_PROXY: true
      run: npm run build -- --win

    - name: Upload build artifacts ${{ matrix.os }}
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.os }}
        path: dist
